platform :ios, '8.0'
target 'QJD-百思不得姐' do
pod 'SDWebImage'
pod 'SDWebImage/GIF' 
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJExtension', '~>3.0.13'
pod 'MJRefresh'
pod 'DACircularProgress', '~>2.3.1'
pod 'pop'
pod 'NJKWebViewProgress'
end
